Repository agflow/dockfmt, pull requests merged in 2019-08, with the labels that each got.

#1 feat(dockfmt): add comment support
  format.go
Labels: size/M

#2 chore: some adjustment for module support
  Makefile
  README.md
  VERSION.txt
  go.mod
Labels: size/XS

#3 feat(dockfmt): enhanced formatter
  format.go
Labels: size/S
